# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_auto_20170603_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products', verbose_name='Imagem'),
        ),
    ]
