# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/products', verbose_name='Imagem'),
        ),
    ]
