# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='nome',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Categoria'),
            preserve_default=False,
        ),
    ]
