# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_banner_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
    ]
