# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170603_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='promovido',
            field=models.BooleanField(default=True, verbose_name='Página principal'),
            preserve_default=False,
        ),
    ]
